# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sancho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_products', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
