# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sancho', '0003_auto_20160807_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Description Larga'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description Corta'),
        ),
        migrations.AlterField(
            model_name='customerdatabase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sancho.Customer', verbose_name='DB Customer'),
        ),
        migrations.AlterField(
            model_name='customerdatabase',
            name='db_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DB Type'),
        ),
        migrations.AlterField(
            model_name='customerdatabase',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DB Host'),
        ),
        migrations.AlterField(
            model_name='customerdatabase',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DB Name'),
        ),
        migrations.AlterField(
            model_name='customerdatabase',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DB Password'),
        ),
        migrations.AlterField(
            model_name='customerdatabase',
            name='port',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DB Port'),
        ),
        migrations.AlterField(
            model_name='customerdatabase',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DB User'),
        ),
        migrations.AlterField(
            model_name='customerstack',
            name='database_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Base de Datos'),
        ),
    ]
