# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_sancho', '0005_auto_20160809_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 9, 15, 13, 6, 881900, tzinfo=utc), verbose_name='Fecha Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='customer_parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sancho.Category', verbose_name='Categoria Padre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='customer_category_id',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='ID Categoria Cliente'),
        ),
    ]
