# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sancho', '0007_auto_20160809_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=6000, null=True, verbose_name='Description Corta'),
        ),
    ]
