# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sancho', '0008_auto_20160809_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Description Larga'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=60000, null=True, verbose_name='Description Corta'),
        ),
    ]
