# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sancho', '0009_auto_20160809_1737'),
        ('app_sancho', '0003_auto_20160720_0936'),
    ]

    operations = [
    ]
