# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccountDataFb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account_amount_spent_fb', models.IntegerField(blank=True, null=True, verbose_name='CustomerAmountSpentFb')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccountsFb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='CustomerIdFb')),
                ('customer_id', models.IntegerField(blank=True, null=True, verbose_name='IdFb')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAdsCreationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='CampaignName')),
                ('ad_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='AdTitle')),
                ('ad_body', models.CharField(blank=True, max_length=100, null=True, verbose_name='AdBody')),
                ('ad_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='AdUrl')),
                ('ad_image_paths', models.CharField(blank=True, max_length=100, null=True, verbose_name='AdImagePaths')),
                ('ad_bid_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='BidType')),
                ('ad_bid_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='BidInfo')),
                ('ad_daily_budget', models.IntegerField(blank=True, null=True, verbose_name='DailyBudget')),
                ('age_min', models.IntegerField(blank=True, null=True, verbose_name='AgeMin')),
                ('age_max', models.IntegerField(blank=True, null=True, verbose_name='AgeMax')),
                ('paused', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paused')),
            ],
        ),
    ]
