# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_galgo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeradscreationdata',
            old_name='ad_daily_budget',
            new_name='adset_field_daily_budget',
        ),
        migrations.RemoveField(
            model_name='customeraccountsfb',
            name='customer_account_id',
        ),
        migrations.RemoveField(
            model_name='customeraccountsfb',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customeradscreationdata',
            name='ad_bid_info',
        ),
        migrations.RemoveField(
            model_name='customeradscreationdata',
            name='ad_bid_type',
        ),
        migrations.RemoveField(
            model_name='customeradscreationdata',
            name='ad_body',
        ),
        migrations.RemoveField(
            model_name='customeradscreationdata',
            name='ad_image_paths',
        ),
        migrations.RemoveField(
            model_name='customeradscreationdata',
            name='ad_title',
        ),
        migrations.RemoveField(
            model_name='customeradscreationdata',
            name='ad_url',
        ),
        migrations.RemoveField(
            model_name='customeradscreationdata',
            name='paused',
        ),
        migrations.AddField(
            model_name='customeraccountsfb',
            name='customer_app_access_token',
            field=models.IntegerField(blank=True, null=True, verbose_name='FbSecret'),
        ),
        migrations.AddField(
            model_name='customeraccountsfb',
            name='customer_app_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='FbId'),
        ),
        migrations.AddField(
            model_name='customeraccountsfb',
            name='customer_app_secret',
            field=models.IntegerField(blank=True, null=True, verbose_name='FbSecret'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='ad_field_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AdMessage'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='ad_field_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AdMessage'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='adcreative_field_caption',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AdMessage'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='adcreative_field_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AdMessage'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='adcreative_field_message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AdMessage'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='adcreative_field_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AdMessage'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='adset_field_bid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='IntegerField'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='adset_field_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AdSetName'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='adset_field_optimization_goal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='AdSetOptimizationGoal'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='adset_filed_billing_event',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Billing'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='campaign_objective',
            field=models.CharField(default='Campaign.Objective.link_clicks', max_length=100, null=True, verbose_name='CampaigObjective'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='campaign_starting_status',
            field=models.CharField(default='Campaign.Objective.link_clicks', max_length=100, null=True, verbose_name='CampaigStatus'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='geo_locations_countries',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GeoLocationCountry'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='target_audience_search_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='customeradscreationdata',
            name='target_audience_type_term',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='q'),
        ),
        migrations.AlterField(
            model_name='customeradscreationdata',
            name='age_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='age_max'),
        ),
        migrations.AlterField(
            model_name='customeradscreationdata',
            name='age_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='age_min'),
        ),
    ]
