# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_galgo', '0003_auto_20160809_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccountsfb',
            name='customer_act_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='AcounttId'),
        ),
        migrations.AddField(
            model_name='customeraccountsfb',
            name='customer_page_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='PageId'),
        ),
        migrations.AlterField(
            model_name='customeraccountsfb',
            name='customer_app_access_token',
            field=models.IntegerField(blank=True, null=True, verbose_name='FbSecretToken'),
        ),
    ]
