# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sancho', '0010_merge'),
        ('app_galgo', '0004_auto_20160809_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_app_id', models.IntegerField(blank=True, null=True, verbose_name='FbId')),
                ('customer_app_secret', models.IntegerField(blank=True, null=True, verbose_name='FbSecret')),
                ('customer_act_id', models.IntegerField(blank=True, null=True, verbose_name='AcounttId')),
                ('customer_page_id', models.IntegerField(blank=True, null=True, verbose_name='PageId')),
                ('customer_app_access_token', models.IntegerField(blank=True, null=True, verbose_name='FbSecretToken')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sancho.Customer')),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomerFbAdCreationData',
            new_name='FbAdCreationData',
        ),
        migrations.RenameModel(
            old_name='CustomerFbAdCreativesCreationData',
            new_name='FbAdCreativesCreationData',
        ),
        migrations.RenameModel(
            old_name='CustomerFbAdSetCreationData',
            new_name='FbAdSetCreationData',
        ),
        migrations.RenameModel(
            old_name='CustomerFbCampaignCreationData',
            new_name='FbCampaignCreationData',
        ),
        migrations.DeleteModel(
            name='CustomerAccountsFb',
        ),
        migrations.AlterField(
            model_name='fbcampaigncreationdata',
            name='customeraccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_galgo.FbAccounts'),
        ),
    ]
