# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_galgo', '0005_auto_20160810_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='CampaignName')),
                ('campaign_objective', models.CharField(default='Campaign.Objective.link_clicks', max_length=100, null=True, verbose_name='CampaigObjective')),
                ('campaign_starting_status', models.CharField(default='Campaign.Status.paused', max_length=100, null=True, verbose_name='CampaigStatus')),
            ],
        ),
        migrations.RemoveField(
            model_name='fbcampaigncreationdata',
            name='customeraccount',
        ),
        migrations.RemoveField(
            model_name='fbaccounts',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='fbadcreationdata',
            name='adcreative',
        ),
        migrations.RemoveField(
            model_name='fbadcreativescreationdata',
            name='adset',
        ),
        migrations.RemoveField(
            model_name='fbadsetcreationdata',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='FbCampaignCreationData',
        ),
        migrations.AddField(
            model_name='fbaccounts',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_galgo.FbCampaign'),
        ),
    ]
