# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_galgo', '0006_auto_20160810_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbaccounts',
            name='campaign',
        ),
        migrations.AddField(
            model_name='fbcampaign',
            name='customeraccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_galgo.FbAccounts'),
        ),
    ]
